
services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_CMD=uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
